version: '3'
# Не очень понял комментарий про контейнеры
# в задании вроде указанно, что должно быть подключено
# 3 контейнера pg_data, static и media
# или имелось ввиду что-то другое?
volumes:
  pg_data:
  static:
  media:

services:
  backend:
    build: ./backend/
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/:/app/result_build/
  nginx:
    image: nginx:1.19.3
    ports:
      - "9000:80"
    volumes:
      - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
