# Generated by Django 3.2.9 on 2023-09-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_rename_favourites_favourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_units',
            field=models.CharField(max_length=100, verbose_name='Единицы измерения'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название ингредиента'),
        ),
    ]
