# Generated by Django 3.2.9 on 2023-09-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20230915_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='amount',
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=7, verbose_name='Количество ингредиента'),
        ),
    ]
