# Generated by Django 3.2.9 on 2023-09-18 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_alter_favourite_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinglist',
            name='name',
        ),
    ]
