# Generated by Django 3.2.9 on 2023-09-18 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0013_remove_shoppinglist_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор списка покупок')),
            ],
            options={
                'verbose_name': 'Список покупок',
                'verbose_name_plural': 'Списки покупок',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='ShoppingCartRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
                ('shopping_cart', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.shoppingcart')),
            ],
        ),
        migrations.RemoveField(
            model_name='shoppinglistrecipe',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='shoppinglistrecipe',
            name='shopping_list',
        ),
        migrations.DeleteModel(
            name='ShoppingList',
        ),
        migrations.DeleteModel(
            name='ShoppingListRecipe',
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='recipe',
            field=models.ManyToManyField(through='recipes.ShoppingCartRecipe', to='recipes.Recipe', verbose_name='рецепты'),
        ),
    ]
