# Generated by Django 3.2.9 on 2023-09-19 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_alter_shoppingcartrecipe_shopping_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcartrecipe',
            name='recipe',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe'),
        ),
    ]
